### ISSUE TITLE
Set esbuild as peer dependency

### ISSUE THREAD

**Issue by PabloSzx** [ambar/es-jest#2]
Could esbuild set as peerDependency instead of dependency? right now to be able to use it we need to use solutions like [`pnpm overrides`](https://pnpm.io/package_json#pnpmoverrides) to force it to use the latest version of esbuild, this would also overrule #1 

and thank you @ambar this solution just works, since I've been trying to use another solutions to use esbuild with jest and this library just works flawlessly

**Comment by ambar** [comment]
Maybe it's a tool issue, if it is yarn, it will automatically de-duplicate.

**Comment by ambar** [comment]
@PabloSzx I think this is fixed in 9703110066736e97e16a3a42872ac55ba16613f8, version is set to ^0.
